export default [
  {
    id: '1',
    cover: 'arrcover',
    title: 'The Complete AR Rahman Show',
    interested: 157,
    teaser: 'https://youtu.be/A5glMV4dLU8?si=HgUzoQ2ccpzbC-fw',
    duration: '2h 30m',
    ageCategory: 5,
    genre: ['Bollywood', 'Retro'],
    languages: ['Hindi', 'Tamil'],
    eventDate: 'Sat 26 Oct 2024',
    priceRange: '₹480 - ₹1580',
    location: 'North Avenue Grounds, Bangalore',
    slot: {
      time: '7:00 pm',
      tickets: 16,
    },
    policies: [
      '• Follow organiser guidelines',
      '• Drugs, smoke, and alcohol consumption prohibited',
      '• Kids below 5 years not recommended',
    ],
    offers: [
      '• Paytm 5% off for min value of ₹1500',
      '• Use HSBC CC for 10% discount on any booking',
    ],
  },
  {
    id: '2',
    cover: 'cricket',
    title: 'India vs New Zealand 2nd Test',
    interested: 289,
    teaser: 'https://youtu.be/testmatch_highlights',
    duration: '5 Days',
    ageCategory: 3,
    genre: ['Sports', 'Cricket'],
    languages: ['English', 'Hindi'],
    eventDate: 'Thu 15 Dec 2024 - Mon 19 Dec 2024',
    priceRange: '₹300 - ₹5000',
    location: 'Eden Gardens, Kolkata',
    slot: {
      time: '9:30 am',
      tickets: 150,
    },
    policies: [
      '• Follow ICC and stadium guidelines',
      '• Outside food & drinks not allowed',
      '• Strict security checks at entry',
    ],
    offers: [
      '• BookMyShow 10% cashback for min purchase of ₹2000',
      '• Use ICICI Debit Card for 5% off',
    ],
  },
  {
    id: '3',
    cover: 'zk',
    title: 'Zakir Khan Live - Tathastu Tour',
    interested: 410,
    teaser: 'https://youtu.be/zakir_khan_tour',
    duration: '1h 45m',
    ageCategory: 16,
    genre: ['Stand-up Comedy'],
    languages: ['Hindi'],
    eventDate: 'Sun 20 Nov 2024',
    priceRange: '₹799 - ₹1999',
    location: 'JLN Auditorium, Delhi',
    slot: {
      time: '8:00 pm',
      tickets: 45,
    },
    policies: [
      '• No recording allowed',
      '• Entry closes 15 minutes after the show starts',
      '• Suitable for audiences 16+',
    ],
    offers: ['• HDFC Credit Card users get ₹200 off', '• Buy 4 tickets & get ₹500 off'],
  },
];
